### ISSUE TITLE
Model versioning

### ISSUE THREAD

**Issue by tsov** [brogrammers/eventhub-api#26]
At one point we need to make our models version compatible like the views and the controllers

**Comment by tsov** [comment]
Oh yeah, and the tests too!

**Comment by foFox** [comment]
We would need to run different databases inside PostgreSQL I think ? Can active record manage that ?

**Comment by tsov** [comment]
It would have to be the same, because we want the same data, but a different interface. The bitch with versioning is: it has to be backwards compatible. Maybe we don't need model versioning, because we can just add functionallity to the models, which can be ignored in older versions.
But tests will need versioning, in controllers & views for example

**Comment by foFox** [comment]
Well at this point we do not need to care that much, as only we are using it. We can push this problem to "before release" .

**Comment by tsov** [comment]
You are write, but I am just mentioning it here, so we won't forget ;)

**Comment by tsov** [comment]
I like the issues section, you can match them with PRs too!

**Comment by tsov** [comment]
Let's not version the models
