### ISSUE TITLE
Add REST API Documentation

### ISSUE THREAD

**Issue by tsov** [brogrammers/eventhub-api#28]
We need a tool to generate HTML documentation of our API, before we start adding a lot of controllers

**Comment by alankehoe** [comment]
Isn't rdoc like javadocs?

Alan Kehoe

**Comment by tsov** [comment]
Look at something like this: https://github.com/Pajk/apipie-rails
so it generates HTML documentation for our public rest api, not documentation for classes and methods.

**Comment by tsov** [comment]
We might be using rdoc once we have more custom libraries.

**Comment by alankehoe** [comment]
Ye I know what you mean that looks like a nice tool... 

Right I am off to Africa now I will be back in two weeks so best if look with finishing off the API looking forward to seeing the finished product.

Alan Kehoe

**Comment by tsov** [comment]
This should do for this issue: https://github.com/brogrammers/eventhub-api/pull/45

**Comment by tsov** [comment]
This is done
